# Problem 6
## Sum square difference

The sum of the squares of the first ten natural numbers is,
1<sup>2</sup>+2<sup>2</sup>+...+10<sup>2</sup>=385

The square of the sum of the first ten natural numbers is,
(1+2+...+10)<sup>2</sup>=55<sup>2</sup>=3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025−385=2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

## 1. Project code

In [4]:
%%time
sumOfSquares = 0
squareOfSum = 0
n = 100
for i in range(1,n+1):
    sumOfSquares += i**2

for j in range(1,n+1):
    squareOfSum += j

x = squareOfSum**2-sumOfSquares
print(x)

84.3 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


84.3 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)